### ISSUE TITLE
Add permission to select folders on external partitions

### ISSUE THREAD

**Issue by haggen88** [Rhyme-Player/Rhyme#121]
Rhyme [Flatpak] does not allow selecting audio libraries outside of the linux file system. In my case I have my library on an NTFS partition, I think it would be very useful if they were allowed in the installation import music from external devices by including the permissions: 

sudo flatpak override com.github.rhyme_player.rhyme --filesystem=host

**Comment by Abdallah-Moh** [comment]
@haggen88 Is this external partition accessible from one of these directory
`/media`
`/run/media`

**Comment by Abdallah-Moh** [comment]
@haggen88 Is this external partition accessible from one of these directory
`/media`
`/run/media`

**Comment by Abdallah-Moh** [comment]
@haggen88 Is this external partition accessible from one of these directory
`/media`
`/run/media`

**Comment by Abdallah-Moh** [comment]
@haggen88 Is this external partition accessible from one of these directory
`/media`
`/run/media`

**Comment by haggen88** [comment]
I reinstalled it and it still can't read files from another partition [I checked the read and write permissions of the ntfs partition and there are no problems]

I checked the permissions with [Flatseal](https://github.com/tchx84/Flatseal)   and it still doesn't allow reading libraries from external partitions. The only thing that differs in Flatseal from another player that if it works is in the section: [Filesystem](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#filesystem) / Other files: home:ro 

![2](https://user-images.githubusercontent.com/68134588/134248516-ac079088-6b47-49ab-90df-6cf02fa58fb0.png)

P.S. you could add a bar to see the status of the scan of the music folder path, and perhaps a button to rescan it.

**Comment by haggen88** [comment]
I confirm that the update fixes this problem, thank you so much!
P.S. Have you thought about adding support for FLAC files?

**Comment by Abdallah-Moh** [comment]
Sure
