### ISSUE TITLE
Support for .flac files

### ISSUE THREAD

**Issue by Suzie97** [Rhyme-Player/Rhyme#128]
Have you thought about adding support for FLAC files?

_Originally posted by @haggen88 in https://github.com/Rhyme-Player/Rhyme/issues/121#issuecomment-924618419_

Adding support for flac files would be useful for a lot of users, especially since Rhyme is a local music player, and some users prefer flac for better audio.

**Comment by Abdallah-Moh** [comment]
@haggen88 , @Suzie97 Done. It will be available in the next release
