### ISSUE TITLE
Player not remembering music location

### ISSUE THREAD

**Issue by grafmariyan** [Rhyme-Player/Rhyme#133]
## Steps to Reproduce

1.
2.
3.

## Platform Information

I'm using ubuntu 21.04 i have music on my usb so i changed the location for music in settings but it's always changing to home/music instead my usb.

**Comment by Abdallah-Moh** [comment]
@grafmariyan  What are you using `flatpak`, `snap` , `from source`, `github releases`

**Comment by grafmariyan** [comment]
Snap

На чт, 23 сеп 2021 г., 12:24 Abdallah Mohammed ***@***.***>
написа:

**Comment by Abdallah-Moh** [comment]
Can u update the snap to version `0.6.4`  and tell me if it works

**Comment by grafmariyan** [comment]
i checked which version i have it's 2.51.7 same. the other problem is
sometimes when i open settings i see a white screen nothing else

На чт, 23.09.2021 г. в 12:49 ч. Abdallah Mohammed ***@***.***>
написа:

**Comment by Abdallah-Moh** [comment]
No update rhyme to version `0.6.4`

**Comment by grafmariyan** [comment]
i updated it now it's working fine thanks

На чт, 23.09.2021 г. в 13:18 ч. Abdallah Mohammed ***@***.***>
написа:

**Comment by Abdallah-Moh** [comment]
No problem
