### ISSUE TITLE
Add a command palette

### ISSUE THREAD

**Issue by Abdallah-Moh** [Rhyme-Player/Rhyme#134]
## Problem
When I want to play a song while I am in the settings tab for example I have to go to the home and search for the song
but a command palette will have a command to play a song so all I have to do is `Ctrl`+`Shift`+`P` 'can be changed from settings' and select play a song then it will list all songs with a search bar at the top,
multiple commands will be added

## A quick mock-up
![Command Palette](https://user-images.githubusercontent.com/77546233/134806000-d00d05ab-b6f0-4bb6-bc04-37914c266580.png)

**Comment by Suzie97** [comment]
This is a nice idea.

Sharing some prior art for reference:

https://user-images.githubusercontent.com/68198116/134502752-192120ad-efeb-4ff6-acd3-02a7e26d0d94.mp4

**Comment by Suzie97** [comment]
I can also see this being useful for managing a large music library. Users can open up the command searchbar and just search for songs, play next, etc. Basically liike Spotlight search but for Rhyme
