### ISSUE TITLE
Artists Tab

### ISSUE THREAD

**Issue by Abdallah-Moh** [Rhyme-Player/Rhyme#19]

**Comment by Abdallah-Moh** [comment]
@bodamat , @Suzie97 should this be included I think that it may affect the appearance having alot of links in the sidebar isn't a good approach if we find another way to include the artists please tell me, and if you find that having an artists tab won't affect the appearance please tell me too

**Comment by bodamat** [comment]
Artist tab is a tab or page what open when click to the music, right?

**Comment by Abdallah-Moh** [comment]
> Artist tab is a tab or page what open when click to the music, right?

A page like albums.

**Comment by bodamat** [comment]
Have just page when all artists are good and just switch between tabs or like between categories, the best approach I think

**Comment by Suzie97** [comment]
Is this issue solved, since you have closed it?

**Comment by Abdallah-Moh** [comment]
NO I re opened it I will add it as a page

**Comment by Suzie97** [comment]
> NO I re opened it I will add it as a page

Yes, I'd like to have a separate artists page. Because sometimes I want to listen to music from my favourite artists.
