### ISSUE TITLE
Add app to `apt`, `yum`, `pacman` and `dnf` for easier installation on Linux

### ISSUE THREAD

**Issue by Abdallah-Moh** [Rhyme-Player/Rhyme#21]
**If some one knows how to do this please comment below**
### Supported package managers

- [ ] `apt`
- [ ] `yum`
- [ ] `pacman` [docs](https://archlinux.org/pacman/repo-add.8.html)
- [ ] `dnf`

**Comment by bodamat** [comment]
Also suggest adding to dnf or yum for Fedora and related. Only this OS work perfect on my PC :)

**Comment by Abdallah-Moh** [comment]
I will

**Comment by Abdallah-Moh** [comment]
@Suzie97, @bodamat, @actuallyabhi : Do you know any docs to follow I cannot find useful docs for now

**Comment by bodamat** [comment]
Unfortunately, I also don't know docs about this topic. If you use Electron then you can read docs there, but only about snap, I remember

**Comment by Abdallah-Moh** [comment]
Well we will support `snap` and `flatpak` soon too

**Comment by Abdallah-Moh** [comment]
We make it easy for our users to download the app

**Comment by Suzie97** [comment]
> @Suzie97, @bodamat, @actuallyabhi : Do you know any docs to follow I cannot find useful docs for now

I don't want to reply with direct links to resources because I know little about electron, JS and other relevant things. But after doing a simple DuckDuckGo! search, I was able to find some relevant links. @Abdallah-Moh you might want to do that yourself or ask someone who is experienced with electron and other web technologies.

Sorry, I couldn't be of much help here.

**Comment by Abdallah-Moh** [comment]
@Suzie97 It does not mater if it is electron or not as my knowlage we upload the packages we built like the `.rpm`,`.pacman`,`.deb`

**Comment by Suzie97** [comment]
> @Suzie97 It does not mater if it is electron or not as my knowledge we upload the packages we built like the `.rpm`,`.pacman`,`.deb`

Thanks, in that case, this is what I could find about deb packaging: https://wiki.debian.org/Packaging

They also have a dedicated JavaScript packaging section: https://wiki.debian.org/Java/Packaging

**Comment by Abdallah-Moh** [comment]
> > @Suzie97 It does not mater if it is electron or not as my knowledge we upload the packages we built like the `.rpm`,`.pacman`,`.deb`
> 
> Thanks, in that case, this is what I could find about deb packaging: https://wiki.debian.org/Packaging
> 
> They also have a dedicated JavaScript packaging section: https://wiki.debian.org/Javascript/Policy

Thanks for the response stop me if I am wrong but I think that these are steps for packaging a `.deb` file

**Comment by Abdallah-Moh** [comment]
@bodamat, Isn't the `*.rpm` files installed with `dnf` right ?

**Comment by bodamat** [comment]
> @bodamat, aren't the `*.rpm` files installed with `dnf` right ?

Yes, right. You can install rpm via dnf

**Comment by gg187on** [comment]
can I take this issue?
